# TODO
name: release

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*.*.*
      - pre-release-*
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --ignore-scripts
      - run: bun run build

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Display dist directory
        run: ls -la dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: dist
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          allowUpdates: true
          draft: false
          prerelease: ${{ startsWith(github.ref, 'refs/tags/pre-release-') }}
